"use strict";
const RANKS="23456789TJQKA", SUITS=["s","h","d","c"], SUIT_ICON={s:"♠",h:"♥",d:"♦",c:"♣"};
const $=id=>document.getElementById(id);
const ui={bankroll:$("bankroll"),pot:$("pot"),street:$("street"),opponentStack:$("opponentStack"),newHand:$("newHand"),board:$("board"),heroCards:$("heroCards"),opponentCards:$("opponentCards"),message:$("message"),fold:$("fold"),checkCall:$("checkCall"),raise:$("raise"),raiseAmount:$("raiseAmount"),raiseValue:$("raiseValue"),equity:$("equity"),winPct:$("winPct"),tiePct:$("tiePct"),potOdds:$("potOdds"),equityRing:$("equityRing"),trainerCard:$("trainerCard"),recommendation:$("recommendation"),explanation:$("explanation"),factors:$("factors"),heroBet:$("heroBet"),opponentBet:$("opponentBet"),tablePot:$("tablePot"),iterations:$("iterations")};
let mode="play", state;
function deck(){return [...RANKS].flatMap(r=>SUITS.map(s=>r+s));}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function combos(a,k){const out=[];function go(start,p){if(p.length===k){out.push(p.slice());return}for(let i=start;i<=a.length-(k-p.length);i++){p.push(a[i]);go(i+1,p);p.pop()}}go(0,[]);return out}
function five(cards){const vals=cards.map(c=>RANKS.indexOf(c[0])+2).sort((a,b)=>b-a), counts=new Map;vals.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const groups=[...counts].sort((a,b)=>b[1]-a[1]||b[0]-a[0]);const flush=cards.every(c=>c[1]===cards[0][1]);let uniq=[...new Set(vals)];if(uniq[0]===14)uniq.push(1);let high=0;for(let i=0;i<=uniq.length-5;i++)if(uniq[i]-uniq[i+4]===4){high=uniq[i];break}if(flush&&high)return[8,high];if(groups[0][1]===4)return[7,groups[0][0],groups[1][0]];if(groups[0][1]===3&&groups[1][1]===2)return[6,groups[0][0],groups[1][0]];if(flush)return[5,...vals];if(high)return[4,high];if(groups[0][1]===3)return[3,groups[0][0],...groups.filter(g=>g[1]===1).map(g=>g[0]).sort((a,b)=>b-a)];const pairs=groups.filter(g=>g[1]===2).map(g=>g[0]).sort((a,b)=>b-a);if(pairs.length===2)return[2,...pairs,groups.find(g=>g[1]===1)[0]];if(pairs.length===1)return[1,pairs[0],...groups.filter(g=>g[1]===1).map(g=>g[0]).sort((a,b)=>b-a)];return[0,...vals]}
function compare(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)!==(b[i]||0))return(a[i]||0)-(b[i]||0)}return 0}
function evaluate(cards){return combos(cards,5).map(five).reduce((best,x)=>compare(x,best)>0?x:best)}
const HANDS=["High card","One pair","Two pair","Three of a kind","Straight","Flush","Full house","Four of a kind","Straight flush"];
function simulate(hole,board,n=5000,opponents=1){const known=new Set([...hole,...board]), available=deck().filter(c=>!known.has(c));let wins=0,ties=0;for(let x=0;x<n;x++){shuffle(available);let p=0;const runout=board.concat(available.slice(p,p+5-board.length));p+=5-board.length;const hero=evaluate(hole.concat(runout));let beaten=false,tied=false;for(let o=0;o<opponents;o++){const rival=evaluate([available[p++],available[p++]].concat(runout)),c=compare(hero,rival);if(c<0){beaten=true;break}if(c===0)tied=true}if(!beaten){if(tied)ties++;else wins++}}return{win:wins/n,tie:ties/n,equity:(wins+ties/2)/n}}
function cardHTML(c,hidden=false){if(hidden)return'<div class="card back" aria-label="Hidden card"></div>';const red=c[1]==="h"||c[1]==="d";return`<div class="card ${red?"red":""}" aria-label="${c}"><span>${c[0]}</span><span class="suit">${SUIT_ICON[c[1]]}</span></div>`}
function fresh(){const d=shuffle(deck());state={deck:d,hero:[d.pop(),d.pop()],villain:[d.pop(),d.pop()],board:[],heroStack:980,villainStack:980,pot:40,heroBet:20,villainBet:20,toCall:0,street:0,active:true,lastAggressor:null};render();updateOdds();ui.message.textContent="You are on the button. Choose your action."}
function render(){ui.bankroll.textContent=state.heroStack.toLocaleString();ui.opponentStack.textContent=state.villainStack.toLocaleString();ui.pot.textContent=ui.tablePot.textContent=state.pot;ui.street.textContent=["Pre-flop","Flop","Turn","River","Showdown"][state.street];ui.heroCards.innerHTML=state.hero.map(c=>cardHTML(c)).join("");ui.opponentCards.innerHTML=state.villain.map(c=>cardHTML(c,state.active)).join("");ui.board.innerHTML=state.board.map(c=>cardHTML(c)).join("")+Array(5-state.board.length).fill('<div class="card back" style="opacity:.18"></div>').join("");ui.heroBet.textContent=`Bet: ${state.heroBet}`;ui.opponentBet.textContent=`Bet: ${state.villainBet}`;ui.checkCall.textContent=state.toCall?`Call ${state.toCall}`:"Check";[ui.fold,ui.checkCall,ui.raise,ui.raiseAmount].forEach(x=>x.disabled=!state.active);ui.raiseAmount.max=Math.max(20,Math.min(300,state.heroStack));ui.trainerCard.classList.toggle("hidden",mode!=="trainer")}
function updateOdds(){if(!state)return;ui.equity.textContent=ui.winPct.textContent="…";setTimeout(()=>{if(!state)return;const o=simulate(state.hero,state.board,+ui.iterations.value);const e=Math.round(o.equity*1000)/10;ui.equity.textContent=`${e}%`;ui.winPct.textContent=`${(o.win*100).toFixed(1)}%`;ui.tiePct.textContent=`${(o.tie*100).toFixed(1)}%`;ui.equityRing.style.setProperty("--equity",e);const call=state.toCall,potOdds=call?call/(state.pot+call):0;ui.potOdds.textContent=call?`${(potOdds*100).toFixed(1)}%`:"Free";if(mode==="trainer")coach(o.equity,potOdds)},10)}
function preflopScore(cards){const a=RANKS.indexOf(cards[0][0])+2,b=RANKS.indexOf(cards[1][0])+2,hi=Math.max(a,b),lo=Math.min(a,b);return hi+lo*.45+(a===b?12:0)+(cards[0][1]===cards[1][1]?2:0)-(Math.max(0,hi-lo-2)*.7)}
function coach(equity,potOdds){let action,why;if(state.toCall&&equity+0.03<potOdds){action="Fold";why=`Your estimated equity is below the ${Math.round(potOdds*100)}% price required to call.`}else if(equity>.66||(state.street===0&&preflopScore(state.hero)>23)){action="Raise";why="Your range is strong enough to build the pot and charge weaker holdings."}else if(state.toCall){action="Call";why="Your equity clears the pot-odds threshold, but the hand is not strong enough to raise confidently."}else if(equity>.55){action="Bet / Raise";why="You appear ahead often enough to pursue value while denying free cards."}else{action="Check";why="Taking a free card controls the pot while preserving your chance to improve."}ui.recommendation.textContent=action;ui.explanation.textContent=why;const rank=state.board.length>=3?HANDS[evaluate(state.hero.concat(state.board))[0]]:`${state.hero[0][0]}${state.hero[1][0]} starting hand`;ui.factors.innerHTML=[rank,`${Math.round(equity*100)}% equity`,state.toCall?`${state.toCall} to call`:"free action",state.street%2?"out of position":"button"].map(x=>`<span>${x}</span>`).join("")}
function commit(amount,who){const stack=who==="hero"?"heroStack":"villainStack",bet=who==="hero"?"heroBet":"villainBet",paid=Math.min(amount,state[stack]);state[stack]-=paid;state[bet]+=paid;state.pot+=paid;return paid}
function opponent(){if(!state.active)return;const strength=state.street?simulate(state.villain,state.board,900).equity:preflopScore(state.villain)/32;if(state.toCall){if(strength<.28&&state.toCall>state.pot*.2){ui.message.textContent="Opponent folds. You win the pot.";finish("hero");return}commit(state.toCall,"villain");state.toCall=0;ui.message.textContent="Opponent calls."}else if(strength>.64&&Math.random()<.55){const bet=Math.min(40+state.street*20,state.villainStack);commit(bet,"villain");state.toCall=bet;ui.message.textContent=`Opponent bets ${bet}.` ;render();updateOdds();return}advance()}
function advance(){state.heroBet=state.villainBet=0;if(state.street===0){state.board.push(state.deck.pop(),state.deck.pop(),state.deck.pop())}else if(state.street<3)state.board.push(state.deck.pop());else{return showdown()}state.street++;render();updateOdds();ui.message.textContent=`${["","Flop","Turn","River"][state.street]} dealt. Your action.`}
function showdown(){state.street=4;state.active=false;const c=compare(evaluate(state.hero.concat(state.board)),evaluate(state.villain.concat(state.board)));const winner=c>0?"hero":c<0?"villain":"tie";if(winner==="hero")state.heroStack+=state.pot;else if(winner==="villain")state.villainStack+=state.pot;else{state.heroStack+=state.pot/2;state.villainStack+=state.pot/2}ui.message.textContent=winner==="tie"?"Split pot — identical five-card hands.":winner==="hero"?`You win with ${HANDS[evaluate(state.hero.concat(state.board))[0]]}!`:`Opponent wins with ${HANDS[evaluate(state.villain.concat(state.board))[0]]}.`;state.pot=0;render();updateOdds()}
function finish(winner){state.active=false;if(winner==="hero")state.heroStack+=state.pot;else state.villainStack+=state.pot;state.pot=0;render()}
ui.newHand.onclick=fresh;ui.fold.onclick=()=>{ui.message.textContent="You fold. Opponent wins the pot.";finish("villain")};ui.checkCall.onclick=()=>{if(state.toCall)commit(state.toCall,"hero");state.toCall=0;render();opponent()};ui.raise.onclick=()=>{const amount=+ui.raiseAmount.value;commit(state.toCall+amount,"hero");state.toCall=amount;render();ui.message.textContent=`You raise ${amount}.`;setTimeout(opponent,350)};ui.raiseAmount.oninput=()=>ui.raiseValue.value=ui.raiseAmount.value;document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));ui.trainerCard.classList.toggle("hidden",mode!=="trainer");if(state)updateOdds();ui.message.textContent=mode==="trainer"?"Trainer enabled — advice will explain each decision.":mode==="odds"?"Odds mode enabled — live equity without coaching.":"Play mode enabled."});
window.PokerEngine={five,evaluate,compare,simulate,deck};
